@baseUrl = http://localhost:8080

### Listar itens pendentes
GET {{baseUrl}}/cozinha/itens-pendentes

### Iniciar preparo do item
PATCH {{baseUrl}}/cozinha/itens/5/iniciar-preparo

### Listar itens em preparo
GET {{baseUrl}}/cozinha/itens-em-preparo

### Marcar item como pronto
PATCH {{baseUrl}}/cozinha/itens/3/marcar-pronto

### Entregar item
PATCH {{baseUrl}}/cozinha/itens/3/entregar